### ISSUE TITLE
Function in Pytorch and caffe support 

### ISSUE THREAD

**Issue by billqxg** [ZhouYanzhao/ORN#13]
This wok is very nice. And thank you very much for release the codes.
My issue is that I can not find orpooling in pytorch version and oralign in caffe version.
Will  you plan to release the corresponding codes in future? @ZhouYanzhao

**Comment by ZhouYanzhao** [comment]
Thanks. The Pytorch version is expected to be upgraded this month, but I have no plans to update Caffe version anytime soon.

**Comment by billqxg** [comment]
That would be nice. Thanks for you reply.
