### ISSUE TITLE
 when i input bash instal.sh, it shows error : orn/src/liborn_kernel.cu.o: 没有那个文件或目录.

### ISSUE THREAD

**Issue by yuy01** [ZhouYanzhao/ORN#15]
Hello,ZhouYanzhao.      
when i input bash instal.sh, it shows error : orn/src/liborn_kernel.cu.o: 没有那个文件或目录.
Can you help me? Thank you!

The instructions:

bash instal.sh
...
...
...
build/temp.linux-x86_64-3.5/home/yangyu/ORN/ORN.pytorch/install/orn/src/liborn_cuda.o orn/src/liborn_kernel.cu.o -o build/lib.linux-x86_64-3.5/orn/_ext/liborn/_liborn.abi3.so
x86_64-linux-gnu-gcc: error: orn/src/liborn_kernel.cu.o: 没有那个文件或目录

**Comment by looput** [comment]
I occur the same problem when I try to install it under anaconda Cuda environment. I solve it by use system default Cuda environment instead of my anaconda's.
