### ISSUE TITLE
Is there any plan to release tensorflow impl. of ORN?

### ISSUE THREAD

**Issue by mikigom** [ZhouYanzhao/ORN#7]
First, thank you for your great research and contribution.

I really need tensorflow implementation of this repo.
Is there any plan to release tensorflow impl.?

If so, I will just wait your release. If not, I have the plan to implement it in long-term on my hands.

**Comment by ZhouYanzhao** [comment]
Thank you! No plans in the near future. It would be great if you can implement it and send me a PR :)

**Comment by mikigom** [comment]
Okay, thank you. :)

**Comment by ymcasky** [comment]
Dear @mikigom  

Have you done tf version?
