### ISSUE TITLE
PyTorch Using filters with kernel_size=1 causes exception.

### ISSUE THREAD

**Issue by utkarsh-VRL** [ZhouYanzhao/ORN#8]
Exception: 'int' object does not support indexing, 
for line _**kernel = kernel_indices[kW][angle][j]**_

Wrapping the kernel_indices for size 1 as a list fixes the issue. New kernel_indices:

        kernel_indices = {
            1: {
                0: [1],
                45: [1],
                90: [1],
                135: [1],
                180: [1],
                225: [1],
                270: [1],
                315: [1]
            },
            3: {
                0: (1,2,3,4,5,6,7,8,9),
                45: (2,3,6,1,5,9,4,7,8),
                90: (3,6,9,2,5,8,1,4,7),
                135: (6,9,8,3,5,7,2,1,4),
                180: (9,8,7,6,5,4,3,2,1),
                225: (8,7,4,9,5,1,6,3,2),
                270: (7,4,1,8,5,2,9,6,3),
                315: (4,1,2,7,5,3,8,9,6)
            }
        }

**Comment by ZhouYanzhao** [comment]
Fixed. Thanks! ea39618ce248d567b69ef3383ee7a4e22e50844d
