### ISSUE TITLE
ORN in detection framework

### ISSUE THREAD

**Issue by zvadaszi** [ZhouYanzhao/ORN#9]
First, thank you for this great contribution.

In your CVPR 2017 poster at Application 5 section there is a comparison of Faster R-CNN detection (bounding box only) with an ORN detection (bounding box + orientation).
Could your elaborate on how you used ORN in a detection framework (maybe you have a github repo) and what dataset was used.

**Comment by ZhouYanzhao** [comment]
@zvadaszi ORN for Aerial Detection is my following work. It is used in a project and it won first place in a remote sensing competition recently (check my [homepage](http://yzhou.work) for more details). I put it on the poster to demonstrate that ORN has great potential for application and I will keep working on it and write a paper to share the idea with the community. Thanks for your interest!

**Comment by zvadaszi** [comment]
Looking forward for the paper.
